Ext.namespace('Js.Center.Statistics.MtByCustomer');Js.Center.Statistics.MtByCustomer.info = function(node){       Js.Center.Statistics.MtByCustomer.querydate = 1;    if (Ext.get("Js.Center.Statistics.MtByCustomer.mainpanel") == null) {                        //============================================================================定义GridPanel相关        // 分页每页显示数量        var _pageSize = -1;        //==============================================================Grid数据定义                Js.Center.Statistics.MtByCustomer.Infostore = new WXTL.Widgets.CommonData.GroupingStore({            proxy: new Ext.data.HttpProxy({                url: Js.Center.Statistics.StatisticsMtURL,                method: "POST"            }),            reader: new Ext.data.JsonReader({                fields: ["datstat","numorder","numuserid", "vc2username", "numall", "numsuccess", "numfailed", "numnoreport", "num_rate", "numdepartid", "vc2departname","vc2opname","num_all_fee"],//["datstat", "numdepartid", "vc2departname", "nummessageformat", "nummtcnt", "numsuccnt", "numfaicnt", "numnocnt", "numsuc_rate"],                root: "data",                id: "numlogid",                totalProperty: "totalCount"                        }),
            sortInfo: {
                field: 'datstat',
                direction: 'ASC'
            },//解决分组无效代码            baseParams: {                start: 0,
                limit: _pageSize,                datcreattimestart: Ext.util.Format.date(WXTL.Common.dateTime.addDay(WXTL.Common.dateTime.getNow(), -7/*减3天*/), 'Y-m-d'),                datcreattimeend: Ext.util.Format.date(WXTL.Common.dateTime.getNow(), 'Y-m-d'),                numsmstype: '',                vc2departname: '',                vc2username: '',                querydate:Js.Center.Statistics.MtByCustomer.querydate ,                flag: 'countbycustomer'            }        });          Js.Center.Statistics.MtByCustomer.Infostore.load({
            params: {
                datcreattimestart: Ext.util.Format.date(WXTL.Common.dateTime.addDay(WXTL.Common.dateTime.getNow(), -7/*减3天*/), 'Y-m-d'),                datcreattimeend: Ext.util.Format.date(WXTL.Common.dateTime.getNow(), 'Y-m-d'),                numsmstype: '',                vc2departname: '',                vc2username: '',                querydate:Js.Center.Statistics.MtByCustomer.querydate ,                flag: 'countbycustomer' 
            }
        });                //==============================================================列选择模式        var sm = new Ext.grid.CheckboxSelectionModel({            dataIndex: "numlogid"        });        //==============================================================列头        var cm = new Ext.grid.ColumnModel([{            header: "统计时间",            tooltip: "统计时间",            dataIndex: "datstat",            sortable: true        }, {            header: "用户名称",            tooltip: "用户名称",            dataIndex: "vc2username",            sortable: true        }, {            header: "部门顺序号",            tooltip: "部门顺序号",            dataIndex: "numorder",            sortable: true        }, {            header: "部门名称",            tooltip: "部门名称",            dataIndex: "vc2departname",            sortable: true        }, {            header: "运营商名称",            tooltip: "运营商名称",            dataIndex: "vc2opname",            sortable: true        }, {            header: "总数",            tooltip: "总数",            dataIndex: "numall",            sortable: true        }, {            header: "成功数",            tooltip: "成功数",            dataIndex: "numsuccess",            sortable: true        }, {            header: "失败数",            tooltip: "失败数",            dataIndex: "numfailed",            sortable: true        }, {            header: "未知数",            tooltip: "未知数",            dataIndex: "numnoreport",            sortable: true        }, {            header: "成功率",            tooltip: "成功率",            dataIndex: "num_rate",            sortable: true//,//            renderer: function(value){//                var rs = value * 100;//                return Math.round(rs * 100) / 100 + "%";//            }        }, {            header: "费用（元）",            tooltip: "费用（元）",            dataIndex: "num_all_fee",            sortable: true        }]);                //==============================================================定义grid        var userGroupGrid = new WXTL.Widgets.CommonGrid.GridPanel({            anchor: '100% 100%',            //pageSize: _pageSize,
			needPage:false,            store: Js.Center.Statistics.MtByCustomer.Infostore,            needMenu: false,            needRightMenu: false,            sm: sm,            cm: cm,            tbar: new Ext.Toolbar({                items: [{                    iconCls: 'exporticon',                    text: "数据导出",                    handler: function(){                    	windowOpen(Js.Center.Statistics.StatisticsMtURL + "?" + "flag=loadbycustomer&start=0&limit=-1&datcreattimestart=" + Ext.get("mtbycustomerdatcreattimestart").getValue() + "&datcreattimeend=" + Ext.get("mtbycustomerdatcreattimeend").getValue() + "&numsmstype=" + "&vc2departname=" + encodeURI(Ext.get("mtbycustomervc2departname").getValue()) + "&vc2username=" + encodeURI(Ext.get("mtbycustomerusername").getValue()));                        //exportData(Js.Center.Statistics.StatisticsMtURL, "flag=loadbycustomer&start=0&limit=-1&datcreattimestart=" + Ext.get("mtbycustomerdatcreattimestart").getValue() + "&datcreattimeend=" + Ext.get("mtbycustomerdatcreattimeend").getValue() + "&numsmstype=" + "&vc2departname=" + Ext.get("mtbycustomervc2departname").getValue() + "&vc2username=" + Ext.get("mtbycustomerusername").getValue());                    }                }]            })        });                        //=============================================================定义formpanel        var mtByDepStartdate = new Ext.form.DateField({            fieldLabel: "开始时间",            format: 'Y-m-d',            labelWidth: 100,            bodyStyle: 'padding:5px 5px 0',            readOnly: true,            emptyText: Ext.util.Format.date(WXTL.Common.dateTime.addDay(WXTL.Common.dateTime.getNow(), -7/*减3天*/), 'Y-m-d'),            fieldLabel: "开始时间",            name: "datcreattimestart",            id: "mtbycustomerdatcreattimestart",            validateOnBlur: false,
            validator: function(){
            var strat_time = Ext.get("mtbycustomerdatcreattimestart").dom.value;
            var end_time = Ext.get("mtbycustomerdatcreattimeend").dom.value;
            if (strat_time <= end_time) {
                return true;
            }
            else {
                return false;
            }
            },
            invalidText: '结束时间不能小于开始时间！'        });        var mtByDepEnddate = new Ext.form.DateField({            fieldLabel: "结束时间",            labelWidth: 100,            format: 'Y-m-d',            bodyStyle: 'padding:5px 5px 0',            readOnly: true,            emptyText: Ext.util.Format.date(WXTL.Common.dateTime.getNow(), 'Y-m-d'),            name: "datcreattimeend",            id: "mtbycustomerdatcreattimeend",            
            validateOnBlur: false,
            validator: function(){
            var strat_time = Ext.get("mtbycustomerdatcreattimestart").dom.value;
            var end_time = Ext.get("mtbycustomerdatcreattimeend").dom.value;
            if (strat_time <= end_time) {
                return true;
            }
            else {
                return false;
            }
            },
            invalidText: '结束时间不能小于开始时间！'        });        var selectPanel = new WXTL.Widgets.CommonPanel.QueryFormPanel({            //查询调用的方法            bodyStyle: "padding:10px 0 10px 15px",            buttonAlign: "center",            queryMethod: "Js.Center.Statistics.MtByCustomer.queryGrid",            items: [{                layout: 'column',                items: [{                    columnWidth: .5,                    layout: 'form',                    defaultType: "textfield",                    //锚点布局-                    defaults: {                        anchor: "90%",                        msgTarget: "side"                    },                    items: [mtByDepStartdate, {                        xtype: "textfield",                        name: "vc2departname",                        id: "mtbycustomervc2departname",                        fieldLabel: "部门名称",
                        regex: WXTL.Common.regex.Illegal,
                        regexText: WXTL.Common.regexText.IllegalText,
                        maxLength: 50,                        maxLengthText:'长度不能超过50！'                    }]                }, {                    columnWidth: .5,                    layout: 'form',                    defaultType: "textfield",                    //锚点布局-                    defaults: {                        anchor: "90%",                        msgTarget: "side"                    },                                        items: [mtByDepEnddate, {                        xtype: "textfield",                        name: "vc2username",                        id: "mtbycustomerusername",                        fieldLabel: "用户名",
                        regex: WXTL.Common.regex.Illegal,
                        regexText: WXTL.Common.regexText.IllegalText,
                        maxLength: 15,                        maxLengthText:'长度不能超过15！'                    }]                }]            }]        });                //============================================================== 定义查询按钮事件方法        Js.Center.Statistics.MtByCustomer.queryGrid = function(){			if (selectPanel.getForm().isValid()) {				var datCreatTimeStart = Ext.get("mtbycustomerdatcreattimestart").getValue();				var datCreatTimeend = Ext.get("mtbycustomerdatcreattimeend").getValue();				var numSmsType = Js.Center.Statistics.MtByCustomer.querydate;				var _vc2departname = Ext.get("mtbycustomervc2departname").getValue();				var _username = Ext.get("mtbycustomerusername").getValue();				var flag = 'countbycustomer';				Js.Center.Statistics.MtByCustomer.Infostore.baseParams = {					flag: flag,					datcreattimestart: datCreatTimeStart,					datcreattimeend: datCreatTimeend,					numsmstype: numSmsType,					vc2departname: _vc2departname,					vc2username: _username				};				Js.Center.Statistics.MtByCustomer.Infostore.load({					params: {						start: 0,						limit: _pageSize					}				});			}        };                //============================================================================定义主panel        Js.Center.Statistics.MtByCustomer.MainPanel = new Ext.Panel({            id: "Js.Center.Statistics.MtByCustomer.mainpanel",            frame: true, // 渲染面板            bodyBorder: false,            border: false,            autoScroll: true, // 自动显示滚动条            layout: "anchor",            defaults: {                collapsible: true // 允许展开和收缩            },            items: [selectPanel, userGroupGrid]        })    };    //============================================================================绑定到center    GridMain(node, Js.Center.Statistics.MtByCustomer.MainPanel, "openroomiconinfo", "Js.Center.Statistics.MtByCustomer.Infostore");};