Ext.namespace('Js.Center.Statistics.MtByUserGroup');Js.Center.Statistics.MtByUserGroup.info = function(node){    Js.Center.Statistics.MtByUserGroup.querydate = 1;    if (Ext.get("Js.Center.Statistics.MtByUserGroup.MainPanel") == null) {        //============================================================================定义GridPanel相关        // 分页每页显示数量        var _pageSize = -1;        //==============================================================Grid数据定义                Js.Center.Statistics.MtByUserGroup.Infostore = new WXTL.Widgets.CommonData.GroupingStore({            proxy: new Ext.data.HttpProxy({                url: Js.Center.Statistics.StatisticsMtURL,                method: "POST"            }),            reader: new Ext.data.JsonReader({                fields: ["numrowasdf","datstat","numorder","vc2departname","vc2opname","vc2svcname","numall","numsuccess","numfailed","num_rate","num_all_fee"],//["datstat","vc2opname", "numdepartid","numorder", "vc2departname", "nummtcnt", "numsuccnt", "numfaicnt", "numnocnt", "numsuc_rate","num_all_fee"],                root: "data",                id: "numrowasdf",                totalProperty: "totalCount"                        }),
            sortInfo: {
                field: 'datstat',
                direction: 'ASC'
            },//解决分组无效代码            baseParams: {                 start: 0,
                limit: _pageSize,                datcreattimestart: Ext.util.Format.date(WXTL.Common.dateTime.addDay(WXTL.Common.dateTime.getNow(), -7/*减3天*/), 'Y-m-d'),                datcreattimeend: Ext.util.Format.date(WXTL.Common.dateTime.getNow(), 'Y-m-d'),                numsmstype: '',                vc2departname: '',                querydate:Js.Center.Statistics.MtByUserGroup.querydate ,                flag: 'countbyusergroup'            }        });          Js.Center.Statistics.MtByUserGroup.Infostore.load({
            params: {
                datcreattimestart: Ext.util.Format.date(WXTL.Common.dateTime.addDay(WXTL.Common.dateTime.getNow(), -7/*减3天*/), 'Y-m-d'),                datcreattimeend: Ext.util.Format.date(WXTL.Common.dateTime.getNow(), 'Y-m-d'),                numsmstype: '',                vc2departname: '',                querydate:Js.Center.Statistics.MtByUserGroup.querydate ,                flag: 'countbyusergroup' 
            }
        });        //==============================================================列选择模式        var sm = new Ext.grid.CheckboxSelectionModel({            dataIndex: "numrowasdf"        });        //==============================================================列头        var cm = new Ext.grid.ColumnModel([{            hidden:true,            header: "统计时间",            tooltip: "统计时间",            dataIndex: "datstat",            sortable: true        }, {            header: "部门名称",            tooltip: "部门名称",            dataIndex: "vc2departname",            sortable: true        }, {            header: "通道名称",            tooltip: "通道名称",            dataIndex: "vc2svcname",            sortable: true        }, {            header: "发送总量(条)",            tooltip: "发送总量(条)",            dataIndex: "numall",            sortable: true        }, {            header: "成功量(条)",            tooltip: "成功量(条)",            dataIndex: "numsuccess",            sortable: true        }]);                //==============================================================定义grid        var userGroupGrid = new WXTL.Widgets.CommonGrid.GridPanel({            anchor: '100% 100%',            //pageSize: _pageSize,
			needPage:false,            store: Js.Center.Statistics.MtByUserGroup.Infostore,            needMenu: false,            needRightMenu: false,            sm: sm,            cm: cm,            tbar: new Ext.Toolbar({                items: [{                    iconCls: 'exporticon',                    text: "数据导出",                    handler: function(){                    	windowOpen(Js.Center.Statistics.StatisticsMtURL + "?" + "flag=loadbyusergroup&start=0&limit=-1&datcreattimestart=" + Ext.get("Js.Center.Statistics.MtByUserGroup.DatStart").getValue() + "&datcreattimeend=" + Ext.get("Js.Center.Statistics.MtByUserGroup.DatEnd").getValue() + "&querydate=" + Js.Center.Statistics.MtByUserGroup.querydate + "&numsmstype=" + "&vc2departname=" + encodeURI(Ext.get("Js.Center.Statistics.MtByUserGroup.DepartName").getValue()));                        //exportData(Js.Center.Statistics.StatisticsMtURL, "flag=loadbyusergroup&start=0&limit=-1&datcreattimestart=" + Ext.get("Js.Center.Statistics.MtByUserGroup.DatStart").getValue() + "&datcreattimeend=" + Ext.get("Js.Center.Statistics.MtByUserGroup.DatEnd").getValue() + "&querydate=" + Js.Center.Statistics.MtByUserGroup.querydate + "&numsmstype=" + "&vc2departname=" + Ext.get("Js.Center.Statistics.MtByUserGroup.DepartName").getValue());                    }                }]            })        });        //=============================================================定义formpanel        var mtBydepStartdate = new Ext.form.DateField({            fieldLabel: "开始时间",            format: 'Y-m-d',            labelWidth: 100,            bodyStyle: 'padding:5px 5px 0',            readOnly: true,            emptyText: Ext.util.Format.date(WXTL.Common.dateTime.addDay(WXTL.Common.dateTime.getNow(), -7/*减3天*/), 'Y-m-d'),            fieldLabel: "开始时间",            name: "datcreattimestart",            id: "Js.Center.Statistics.MtByUserGroup.DatStart",            validateOnBlur: false,
            validator: function(){
            var strat_time = Ext.get("Js.Center.Statistics.MtByUserGroup.DatStart").dom.value;
            var end_time = Ext.get("Js.Center.Statistics.MtByUserGroup.DatEnd").dom.value;
            if (strat_time <= end_time) {
                return true;
            }
            else {
                return false;
            }
            },
            invalidText: '结束时间不能小于开始时间！'        });        var mtBydepEnddate = new Ext.form.DateField({            fieldLabel: "结束时间",            labelWidth: 100,            format: 'Y-m-d',            bodyStyle: 'padding:5px 5px 0',            readOnly: true,            emptyText: Ext.util.Format.date(WXTL.Common.dateTime.getNow(), 'Y-m-d'),            name: "datcreattimeend",            id: "Js.Center.Statistics.MtByUserGroup.DatEnd",            validateOnBlur: false,
            validator: function(){
            var strat_time = Ext.get("Js.Center.Statistics.MtByUserGroup.DatStart").dom.value;
            var end_time = Ext.get("Js.Center.Statistics.MtByUserGroup.DatEnd").dom.value;
            if (strat_time <= end_time) {
                return true;
            }
            else {
                return false;
            }
            },
            invalidText: '结束时间不能小于开始时间！'        });        var selectPanel = new WXTL.Widgets.CommonPanel.QueryFormPanel({            bodyStyle: "padding:10px 0 10px 15px",            buttonAlign: "center",            //查询调用的方法            queryMethod: "Js.Center.Statistics.MtByUserGroup.queryGrid",                items: [{                    layout: 'column',                    items: [{                        columnWidth: .5,                        layout: 'form',                        defaultType: "textfield",                        //锚点布局-                        defaults: {                            anchor: "90%",                            msgTarget: "side"                        },                        items: [mtBydepStartdate, {                            xtype: "textfield",                            name: "vc2departname",                            id: "Js.Center.Statistics.MtByUserGroup.DepartName",                            fieldLabel: "部门名称",
                            regex: WXTL.Common.regex.Illegal,
                            regexText: WXTL.Common.regexText.IllegalText,
                            maxLength: 50,                            maxLengthText:'长度不能超过50！'                        }]                    }, {                        columnWidth: .5,                        layout: 'form',                        defaultType: "textfield",                        //锚点布局-                        defaults: {                            anchor: "90%",                            msgTarget: "side"                        },                                                items: [mtBydepEnddate]                    }]                }]        });                //============================================================== 定义查询按钮事件方法        Js.Center.Statistics.MtByUserGroup.queryGrid = function(){			if (selectPanel.getForm().isValid()) {				var datCreatTimeStart = Ext.get("Js.Center.Statistics.MtByUserGroup.DatStart").getValue();				var datCreatTimeend = Ext.get("Js.Center.Statistics.MtByUserGroup.DatEnd").getValue();				var numSmsType = "";				var _vc2departname = Ext.get("Js.Center.Statistics.MtByUserGroup.DepartName").getValue();				var flag = 'countbyusergroup';				Js.Center.Statistics.MtByUserGroup.Infostore.baseParams = {					flag: flag,					datcreattimestart: datCreatTimeStart,					datcreattimeend: datCreatTimeend,					numsmstype: numSmsType,					vc2departname: _vc2departname,					querydate: Js.Center.Statistics.MtByUserGroup.querydate				};				Js.Center.Statistics.MtByUserGroup.Infostore.load({					params: {						start: 0,						limit: _pageSize					}				});			}        };                //============================================================================定义主panel        Js.Center.Statistics.MtByUserGroup.MainPanel = new Ext.Panel({            id: "Js.Center.Statistics.MtByUserGroup.MainPanel",            frame: true, // 渲染面板            bodyBorder: false,            border: false,            autoScroll: true, // 自动显示滚动条            layout: "anchor",            defaults: {                collapsible: true // 允许展开和收缩            },            items: [selectPanel, userGroupGrid]        })    };    //============================================================================绑定到center    GridMain(node, Js.Center.Statistics.MtByUserGroup.MainPanel, "openroomiconinfo", "Js.Center.Statistics.MtByUserGroup.Infostore");};