Ext.namespace('Js.Center.Statistics.MtByDepartment');Js.Center.Statistics.MtByDepartment.info = function(node){    Js.Center.Statistics.MtByDepartment.querydate = 1;    if (Ext.get("Js.Center.Statistics.MtByDepartment.MainPanel") == null) {        //============================================================================定义GridPanel相关        // 分页每页显示数量        var _pageSize = -1;        //==============================================================Grid数据定义                Js.Center.Statistics.MtByDepartment.Infostore = new WXTL.Widgets.CommonData.GroupingStore({            proxy: new Ext.data.HttpProxy({                url: Js.Center.Statistics.StatisticsMtURL,                method: "POST"            }),            reader: new Ext.data.JsonReader({                fields: ["numrowasdf","datstat","numorder","vc2departname","vc2opname","numall","numsuccess","numfailed","numnoreport","num_rate","num_all_fee"],//["datstat","vc2opname", "numdepartid","numorder", "vc2departname", "nummtcnt", "numsuccnt", "numfaicnt", "numnocnt", "numsuc_rate","num_all_fee"],                root: "data",                id: "numrowasdf",                totalProperty: "totalCount"                        }),
            sortInfo: {
                field: 'datstat',
                direction: 'ASC'
            },//解决分组无效代码            baseParams: {                 start: 0,
                limit: _pageSize,                datcreattimestart: Ext.util.Format.date(WXTL.Common.dateTime.addDay(WXTL.Common.dateTime.getNow(), -7/*减3天*/), 'Y-m-d'),                datcreattimeend: Ext.util.Format.date(WXTL.Common.dateTime.getNow(), 'Y-m-d'),                numsmstype: '',                vc2departname: '',                querydate:Js.Center.Statistics.MtByDepartment.querydate ,                flag: 'countbydepartment'            }        });          Js.Center.Statistics.MtByDepartment.Infostore.load({
            params: {
                datcreattimestart: Ext.util.Format.date(WXTL.Common.dateTime.addDay(WXTL.Common.dateTime.getNow(), -7/*减3天*/), 'Y-m-d'),                datcreattimeend: Ext.util.Format.date(WXTL.Common.dateTime.getNow(), 'Y-m-d'),                numsmstype: '',                vc2departname: '',                querydate:Js.Center.Statistics.MtByDepartment.querydate ,                flag: 'countbydepartment' 
            }
        });        //==============================================================列选择模式        var sm = new Ext.grid.CheckboxSelectionModel({            dataIndex: "numrowasdf"        });        //==============================================================列头        var cm = new Ext.grid.ColumnModel([{            header: "统计时间",            tooltip: "统计时间",            dataIndex: "datstat",            sortable: true        }, {            header: "部门顺序号",            tooltip: "部门顺序号",            dataIndex: "numorder",            sortable: true        }, {            header: "部门名称",            tooltip: "部门名称",            dataIndex: "vc2departname",            sortable: true        }, {            header: "运营商名称",            tooltip: "运营商名称",            dataIndex: "vc2opname",            sortable: true        }, {            header: "总数",            tooltip: "总数",            dataIndex: "numall",            sortable: true        }, {            header: "成功数",            tooltip: "成功数",            dataIndex: "numsuccess",            sortable: true        }, {            header: "失败数",            tooltip: "失败数",            dataIndex: "numfailed",            sortable: true        }, {            header: "未知数",            tooltip: "未知数",            dataIndex: "numnoreport",            sortable: true        }, {            header: "成功率",            tooltip: "成功率",            dataIndex: "num_rate",            sortable: true//,//            renderer: function(value){//                var rs = value * 100;//                return Math.round(rs * 100) / 100 + "%";//            }        }, {            header: "费用（元）",            tooltip: "费用（元）",            dataIndex: "num_all_fee",            sortable: true        }]);                //==============================================================定义grid        var userGroupGrid = new WXTL.Widgets.CommonGrid.GridPanel({            anchor: '100% 100%',            //pageSize: _pageSize,
			needPage:false,            store: Js.Center.Statistics.MtByDepartment.Infostore,            needMenu: false,            needRightMenu: false,            sm: sm,            cm: cm,            tbar: new Ext.Toolbar({                items: [{                    iconCls: 'exporticon',                    text: "数据导出（按天）",                    handler: function(){                    	windowOpen(Js.Center.Statistics.StatisticsMtURL + "?" + "flag=loadbydepartment&start=0&limit=-1&datcreattimestart=" + Ext.get("mtbydepartmentdatcreattimestart").getValue() + "&datcreattimeend=" + Ext.get("mtbydepartmentdatcreattimeend").getValue() + "&querydate=" + Js.Center.Statistics.MtByDepartment.querydate + "&numsmstype=" + "&vc2departname=" + encodeURI(Ext.get("mtbydepartmentvc2departname").getValue()));                        //exportData(Js.Center.Statistics.StatisticsMtURL, "flag=loadbydepartment&start=0&limit=-1&datcreattimestart=" + Ext.get("mtbydepartmentdatcreattimestart").getValue() + "&datcreattimeend=" + Ext.get("mtbydepartmentdatcreattimeend").getValue() + "&querydate=" + Js.Center.Statistics.MtByDepartment.querydate + "&numsmstype=" + "&vc2departname=" + Ext.get("mtbydepartmentvc2departname").getValue());                    }                }//                ,{//                    iconCls: 'exporticon',//                    text: "数据导出（按部门）",//                    handler: function(){//                    	windowOpen(Js.Center.Statistics.StatisticsMtURL + "?" + "flag=loadbydepartmentallday&start=0&limit=-1&datcreattimestart=" + Ext.get("mtbydepartmentdatcreattimestart").getValue() + "&datcreattimeend=" + Ext.get("mtbydepartmentdatcreattimeend").getValue() + "&querydate=" + Js.Center.Statistics.MtByDepartment.querydate + "&numsmstype=" + "&vc2departname=" + encodeURI(Ext.get("mtbydepartmentvc2departname").getValue()));//                        //exportData(Js.Center.Statistics.StatisticsMtURL, "flag=loadbydepartmentallday&start=0&limit=-1&datcreattimestart=" + Ext.get("mtbydepartmentdatcreattimestart").getValue() + "&datcreattimeend=" + Ext.get("mtbydepartmentdatcreattimeend").getValue() + "&querydate=" + Js.Center.Statistics.MtByDepartment.querydate + "&numsmstype=" + "&vc2departname=" + Ext.get("mtbydepartmentvc2departname").getValue());//                    }//                }                ]            })        });        //=============================================================定义formpanel        var mtBydepStartdate = new Ext.form.DateField({            fieldLabel: "开始时间",            format: 'Y-m-d',            labelWidth: 100,            bodyStyle: 'padding:5px 5px 0',            readOnly: true,            emptyText: Ext.util.Format.date(WXTL.Common.dateTime.addDay(WXTL.Common.dateTime.getNow(), -7/*减3天*/), 'Y-m-d'),            fieldLabel: "开始时间",            name: "datcreattimestart",            id: "mtbydepartmentdatcreattimestart",            validateOnBlur: false,
            validator: function(){
            var strat_time = Ext.get("mtbydepartmentdatcreattimestart").dom.value;
            var end_time = Ext.get("mtbydepartmentdatcreattimeend").dom.value;
            if (strat_time <= end_time) {
                return true;
            }
            else {
                return false;
            }
            },
            invalidText: '结束时间不能小于开始时间！'        });        var mtBydepEnddate = new Ext.form.DateField({            fieldLabel: "结束时间",            labelWidth: 100,            format: 'Y-m-d',            bodyStyle: 'padding:5px 5px 0',            readOnly: true,            emptyText: Ext.util.Format.date(WXTL.Common.dateTime.getNow(), 'Y-m-d'),            name: "datcreattimeend",            id: "mtbydepartmentdatcreattimeend",            validateOnBlur: false,
            validator: function(){
            var strat_time = Ext.get("mtbydepartmentdatcreattimestart").dom.value;
            var end_time = Ext.get("mtbydepartmentdatcreattimeend").dom.value;
            if (strat_time <= end_time) {
                return true;
            }
            else {
                return false;
            }
            },
            invalidText: '结束时间不能小于开始时间！'        });        var selectPanel = new WXTL.Widgets.CommonPanel.QueryFormPanel({            bodyStyle: "padding:10px 0 10px 15px",            buttonAlign: "center",            //查询调用的方法            queryMethod: "Js.Center.Statistics.MtByDepartment.queryGrid",                items: [{                    layout: 'column',                    items: [{                        columnWidth: .5,                        layout: 'form',                        defaultType: "textfield",                        //锚点布局-                        defaults: {                            anchor: "90%",                            msgTarget: "side"                        },                        items: [mtBydepStartdate, {                            xtype: "textfield",                            name: "vc2departname",                            id: "mtbydepartmentvc2departname",                            fieldLabel: "部门名称",
                            regex: WXTL.Common.regex.Illegal,
                            regexText: WXTL.Common.regexText.IllegalText,
                            maxLength: 50,                            maxLengthText:'长度不能超过50！'                        }]                    }, {                        columnWidth: .5,                        layout: 'form',                        defaultType: "textfield",                        //锚点布局-                        defaults: {                            anchor: "90%",                            msgTarget: "side"                        },                                                items: [mtBydepEnddate]                    }]                }]        });                //============================================================== 定义查询按钮事件方法        Js.Center.Statistics.MtByDepartment.queryGrid = function(){			if (selectPanel.getForm().isValid()) {				var datCreatTimeStart = Ext.get("mtbydepartmentdatcreattimestart").getValue();				var datCreatTimeend = Ext.get("mtbydepartmentdatcreattimeend").getValue();				var numSmsType = "";				var _vc2departname = Ext.get("mtbydepartmentvc2departname").getValue();				var flag = 'countbydepartment';				Js.Center.Statistics.MtByDepartment.Infostore.baseParams = {					flag: flag,					datcreattimestart: datCreatTimeStart,					datcreattimeend: datCreatTimeend,					numsmstype: numSmsType,					vc2departname: _vc2departname,					querydate: Js.Center.Statistics.MtByDepartment.querydate				};				Js.Center.Statistics.MtByDepartment.Infostore.load({					params: {						start: 0,						limit: _pageSize					}				});			}        };                //============================================================================定义主panel        Js.Center.Statistics.MtByDepartment.MainPanel = new Ext.Panel({            id: "Js.Center.Statistics.MtByDepartment.MainPanel",            frame: true, // 渲染面板            bodyBorder: false,            border: false,            autoScroll: true, // 自动显示滚动条            layout: "anchor",            defaults: {                collapsible: true // 允许展开和收缩            },            items: [selectPanel, userGroupGrid]        })    };    //============================================================================绑定到center    GridMain(node, Js.Center.Statistics.MtByDepartment.MainPanel, "openroomiconinfo", "Js.Center.Statistics.MtByDepartment.Infostore");};